### ISSUE TITLE
Could you make an English version of this?

### ISSUE THREAD

**Issue by skilomlg** [very-strange-developer/VITS_ColabNotebooks#1]
Hi, I found this when searching on GitHub. However, I have no idea how to use these colab notebooks as they are in Korean. I only know English. If you can’t make an English version of these notebooks, that’s fine. I just want to know how to use it. Google translate didn’t help much.

**Comment by politics-in-the-pond** [comment]
Okay, if I have time later, I will write the English version too.
Thank you for watching my github page.

**Comment by very-strange-developer** [comment]
Okay, if I have time later, I will write the English version too.
Thank you for visiting my github page.

**Comment by skilomlg** [comment]
No problem man, If I can get these colabs to work, You're a life saver.
I was searching for something like this. But vits is so new so it wasn't easy. 

Thank you.
