### ISSUE TITLE
Why is my model trash after training?

### ISSUE THREAD

**Issue by skilomlg** [very-strange-developer/VITS_ColabNotebooks#5]
I just tested the english training colab, and it works. However after it finished training, My model sounds terrible. It pronounces only a little but not a lot and there's a lot of buzzing noise along with other noise. It really disappoints me. I have a dataset I made and had a friend train it on vits. it sounds good. Is there any way I can fix this particular model problem? perhaps maybe because it was trained on english_cleaners2 instead of english_cleaners? Maybe there's something I've done wrong?

**Comment by very-strange-developer** [comment]
As far as I know, english_cleaners2 is the VITS`s default value for English.

**Comment by very-strange-developer** [comment]
Please check if you used G_0.pth as a model and if you had enough epochs.

**Comment by very-strange-developer** [comment]
Have you preprocessed transcript for English colab notebook once again?
I changed cleaner for english. 'basic_cleaners' -> 'english_cleaners2'.

**Comment by skilomlg** [comment]
> Have you preprocessed transcript for English colab notebook once again? I changed cleaner for english. 'basic_cleaners' -> 'english_cleaners2'.

I made sure not to change it. I let it train over night and it stopped training after reaching 10,000 epochs.

**Comment by skilomlg** [comment]
Maybe there wasn't enough data. I had 120 .wav files in total

**Comment by skilomlg** [comment]
Oh my god, I'm so mad. I tried training another dataset and yeah. It's failing to download the script files properly and I have to download the files and constantly replace them and run the code blocks again. I replaced and fixed every doctype error and got this while training. This makes me want to throw my macbook out the window. :(

`INFO:Drake:Saving model and optimizer state at iteration 1 to /content/drive/My Drive/colab/outdir/Drake/G_0.pth
INFO:Drake:Saving model and optimizer state at iteration 1 to /content/drive/My Drive/colab/outdir/Drake/D_0.pth

---------------------------------------------------------------------------

UnpicklingError                           Traceback (most recent call last)

[<ipython-input-9-d81cf0f0ca46>](https://localhost:8080/#) in <module>()
    289 
    290 if __name__ == "__main__":
--> 291   main()

6 frames

[/usr/local/lib/python3.7/dist-packages/torch/_utils.py](https://localhost:8080/#) in reraise(self)
    432             # instantiate since we don't know how to
    433             raise RuntimeError(msg) from None
--> 434         raise exception
    435 
    436 

UnpicklingError: Caught UnpicklingError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/vits/data_utils.py", line 94, in __getitem__
    return self.get_audio_text_pair(self.audiopaths_and_text[index])
  File "/content/vits/data_utils.py", line 62, in get_audio_text_pair
    spec, wav = self.get_audio(audiopath)
  File "/content/vits/data_utils.py", line 74, in get_audio
    spec = torch.load(spec_filename)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.`

**Comment by very-strange-developer** [comment]
Did you delete the metadata in the wav file?
If there is metadata in the wav file, audio cannot be loaded.

**Comment by very-strange-developer** [comment]
Or make sure that the audio file path of transcript is correct.

**Comment by very-strange-developer** [comment]
In the case of doctype errors, they didn't occur before, but they started to occur recently.
Maybe Google changed something on google drive.

**Comment by very-strange-developer** [comment]
Most of the logic is the same as the original VITS, so if it doesn't work on the colab notebook, it won't work the same way in most situations. (except doctype error)

**Comment by skilomlg** [comment]
> Did you delete the metadata in the wav file?
> If there is metadata in the wav file, audio cannot be loaded.

What is metadata? Could you please tell me what that is? Is it pitch differences?

**Comment by skilomlg** [comment]
I fixed the problem with that error, I had a space in my filelist.txt. An empty line, I removed the space and it started to run without the dreadful error.

**Comment by skilomlg** [comment]
Please keep this issue open as I might have more issues that occur.

**Comment by skilomlg** [comment]
May  ask if it's possible to update the colabs to download stuff properly?

I get this error when synthesizing sometimes
`---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-5-0210e5c80e7f>](https://localhost:8080/#) in <module>()
     17 import utils
     18 from data_utils import TextAudioLoader, TextAudioCollate, TextAudioSpeakerLoader, TextAudioSpeakerCollate
---> 19 from models import SynthesizerTrn
     20 from text.symbols import symbols
     21 from text import text_to_sequence

1 frames

[/content/vits/monotonic_align/__init__.py](https://localhost:8080/#) in <module>()
      1 import numpy as np
      2 import torch
----> 3 from monotonic_align.core import maximum_path_c
      4 
      5 

ModuleNotFoundError: No module named 'monotonic_align.core'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`

**Comment by very-strange-developer** [comment]
I solved the download error a few days ago.
